#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/linphone-el

FLAVOR=$1
PACKAGE=linphone-el

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

install -m 755 -d ${ELCDIR}
cd ${ELDIR}
FILES=`echo *.el Makefile`
cd ${ELCDIR}

if [ ${FLAVOR} != emacs ]; then
    for file in $FILES
    do ln -s ../../../emacs/site-lisp/${PACKAGE}/$file
    done
fi

make -ks EMACS=${FLAVOR} > CompilationLog 2>&1
if [ ${FLAVOR} != emacs ]
then rm -f Makefile make-loaddefs.el
fi
gzip -9 -f ${ELCDIR}/CompilationLog

exit 0
