#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/linphone-el

FLAVOR=$1
PACKAGE=linphone-el

echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}

if [ ${FLAVOR} = emacs ]; then
    rm -f /usr/share/${FLAVOR}/site-lisp/${PACKAGE}/*.elc
    rm -f /usr/share/${FLAVOR}/site-lisp/${PACKAGE}/linphone-loaddefs.el
    rm -f /usr/share/${FLAVOR}/site-lisp/${PACKAGE}/CompilationLog.gz
else rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
fi
